# Rasm File
format = "jpg"
size = [1080, 1080]
color = [255, 255, 255, 255]
[[assets]]
id = "logo"
src = "logo.svg"

[[objects]]
name = "image"
src = "pic.jpg"
origin = [0, 0]
resize = [100, 0]
[[objects]]
name = "rect"
color = [0, 150, 75, 255]
origin = [50.4, 0]
offset = [57, 100]
[[objects]]
name = "image"
src = "back.png"
origin = [0, 0]
[[objects]]
name = "image"
src = "logo-small-s.png"
origin = [0, 0]
[[objects]]
name = "image"
src = "logo-small.png"
origin = [0, 0]
[[objects]]
name = "image"
src = "logo-medium.png"
origin = [0, 0]
[[objects]]
name = "image"
src = "logo-big.png"
origin = [0, 0]