format = "jpg"
size = [1080, 1080]
color = [255, 255, 255, 255]
[[shapes]]
name = "image"
path = "pic.jpg"
origin = [0, 0]
resize = [100, 0]
[[shapes]]
name = "rect"
color = [0, 150, 75, 255]
origin = [50.4, 0]
offset = [57, 100]
[[shapes]]
name = "image"
path = "back.png"
origin = [0, 0]
[[shapes]]
name = "image"
path = "logo-small-s.png"
origin = [0, 0]
[[shapes]]
name = "image"
path = "logo-small.png"
origin = [0, 0]
[[shapes]]
name = "image"
path = "logo-medium.png"
origin = [0, 0]
[[shapes]]
name = "image"
path = "logo-big.png"
origin = [0, 0]